### ISSUE TITLE
Throw invalid usage when providing an empty word

### ISSUE THREAD

**Issue by felipemfp** [felipemfp/sinonimos-cli#11]
### Briefing

We should called `app.PrintHelp()` and `os.Exit(1)` if `*word == ""`.

### Tasks

- [ ] Handle empty word

**Comment by ganes1410** [comment]
Can i take this ?

**Comment by ganes1410** [comment]
@felipemfp But when i run `make dep-ensure`

I get this.
`
/bin/sh: 1: dep: not found
Makefile:16: recipe for target 'dep-ensure' failed
make: *** [dep-ensure] Error 127
`

**Comment by felipemfp** [comment]
> @felipemfp But when i run `make dep-ensure`
> 
> I get this.
> `/bin/sh: 1: dep: not found Makefile:16: recipe for target 'dep-ensure' failed make: *** [dep-ensure] Error 127`

Do you have dep installed? [See here how to install](https://github.com/golang/dep/blob/master/docs/installation.md)

**Comment by felipemfp** [comment]
Fix by @imjorge :tada:
