### ISSUE TITLE
Add ability to search for expressions like "no entanto"

### ISSUE THREAD

**Issue by felipemfp** [felipemfp/sinonimos-cli#12]
### Briefing

For now, we are only able to handle a single word. It would be nice to handle expressions as well.

For example, "no entanto" should fetch synonyms of "https://www.sinonimos.com.br/no-entanto/".

I think we could just *slugify* the parameter using something like [go-slugify](https://github.com/metal3d/go-slugify) 

### Tasks

- [ ] Change "PALAVRA" parameter for "EXPRESSION" 
- [ ] Add ability to search for expressions

**Comment by bartier** [comment]
Can I work on this?

**Comment by felipemfp** [comment]
Sure, @bartier. Go ahead!
