### ISSUE TITLE
Print message when there's no synonyms

### ISSUE THREAD

**Issue by felipemfp** [felipemfp/sinonimos-cli#21]
### Briefing

The current implementation does not care if there is any synonyms, it just print what it founds. But for the end user, would be nice to print a message when there is no synonyms. For example, try: `sinonimos akjgleahgabg`

### Tasks

- [x] Implement a verification if there's any synonyms
  - Print: "Desculpa, mas não encontramos nenhum sinônimo"
  - `os.Exit(1)`

**Comment by ulziibuyan** [comment]
Me, me, me!

**Comment by felipemfp** [comment]
All yours, @ulziibuyan
