### ISSUE TITLE
Add ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by felipemfp** [felipemfp/sinonimos-cli#27]
### Briefing

GitHub offers a way to create `ISSUE_TEMPLATE.md` that could be used for standardization.

We could have one like:

```md
### Briefing

Brief description of this issue or feature.

### Tasks

- [ ] Task 1
- [ ] Task 2
```

### Tasks

- [ ] [Create](https://help.github.com/articles/manually-creating-a-single-issue-template-for-your-repository/) the ISSUE_TEMPLATE.md above

**Comment by 73VW** [comment]
I'll take it!

**Comment by felipemfp** [comment]
Go ahead, @73VW
