### ISSUE TITLE
Words without "sentido" element didn't work

### ISSUE THREAD

**Issue by chicobentojr** [felipemfp/sinonimos-cli#28]
### Briefing

Looking for the word [debelar](https://www.sinonimos.com.br/debelar/) has returned nothing: 
![image](https://user-images.githubusercontent.com/9325152/47716613-070b9b00-dc22-11e8-91b7-8f8e5a7bab06.png)

This happens because the word doesn't have the `<div class="sentido">...</div>` element:

![image](https://user-images.githubusercontent.com/9325152/47716781-7a151180-dc22-11e8-95bd-2d7c63adf3b8.png)

### Tasks

- [x] Fix to scrape synonyms even without meaning (see https://github.com/felipemfp/sinonimos-cli/issues/28#issuecomment-434275618)

**Comment by felipemfp** [comment]
If you or anyone wants to try this one, I think we just need to [scrape the synonyms](https://github.com/felipemfp/sinonimos-cli/blob/2638a02a59c9ad13112d5d8fdb54b15378c99b2f/src/sinonimos/main.go#L85) outside of this `if`:

https://github.com/felipemfp/sinonimos-cli/blob/2638a02a59c9ad13112d5d8fdb54b15378c99b2f/src/sinonimos/main.go#L82

**Comment by vincealdrin** [comment]
I can take this!
