### ISSUE TITLE
Program doesn't treat words with special characters

### ISSUE THREAD

**Issue by edusporto** [felipemfp/sinonimos-cli#32]
## 🔱 Issue subject
- [x] 👽 **Bug**
- [ ] 🔥 **New feature proposal**
- [ ] 💭 **Idea/need**
- [ ] ❓ **Other**

### 👽 **Bug**

1. Searching for a word containing a character not included in the ASCII table, such as "á", "ç", and "ã".

![image](https://user-images.githubusercontent.com/30930225/47884857-33393e80-de11-11e8-9418-bf086a49254b.png)

**Comment by felipemfp** [comment]
@edusporto, do you want to help to fix it? I think we just need a `slugify` function here: 

https://github.com/felipemfp/sinonimos-cli/blob/master/src/sinonimos/main.go#L60

If you would use [`go-slugify`](https://github.com/metal3d/go-slugify), it should look something like this:

```go
resp, err := http.Get(fmt.Sprintf("https://www.sinonimos.com.br/%s/", slugify.Marshal(expression)))
```

**Comment by edusporto** [comment]
Sure!
