### ISSUE TITLE
Questions about creating README.md

### ISSUE THREAD

**Issue by bartier** [felipemfp/sinonimos-cli#38]
## 📛 Global notes

Please do not create an issue before giving a look at the others. Someone may have thought about the same thing as you or may have had the same problem.

Please provide enough information so that others can understand your issue:

## 🔱 Issue subject

- [ ] 👽 **Bug**
- [ ] 🔥 **New feature proposal**
- [ ] 💭 **Idea/need**
- [X] ❓ **Other**

#### Subject
Oi Felipe tudo bom?

O que você utilizou para criar o gif do README? Como você conseguiu criar aquele efeito de aparecer na frente o que deveria ser escrito?

Achei super legal e gostaria de aplicar em um projeto pessoal.

Obrigado desde já!

## ➕ More
If you need help or have doubts, ping team members (@felipemfp)
Otherwise, you can write here anything that is not covered above.

**Comment by felipemfp** [comment]
Tudo bom :v:

É Terminal do Ubuntu + `zsh` + [`oh-my-zsh`](https://github.com/robbyrussell/oh-my-zsh). E gravei com o [Peek](https://github.com/phw/peek).

O efeito de aparecer a sugestão na frente é um plugin: [`zsh-autosuggestions`](https://github.com/zsh-users/zsh-autosuggestions).
