### ISSUE TITLE
Add colors to output

### ISSUE THREAD

**Issue by felipemfp** [felipemfp/sinonimos-cli#5]
### Briefing

The current output is a little too plain... Maybe some colors would help.

Perhaps https://github.com/logrusorgru/aurora is the right choice.

### Tasks

- [x] Add colors for [different "meanings"](https://github.com/felipemfp/sinonimos-cli/blob/master/src/sinonimos/main.go#L50)

**Comment by ulziibuyan** [comment]
Hey, there! I would like to work on this too.

**Comment by felipemfp** [comment]
Go ahead, @ulziibuyan!
