### ISSUE TITLE
Add ability to print current version

### ISSUE THREAD

**Issue by felipemfp** [felipemfp/sinonimos-cli#6]
### Briefing

We should have a `version` command or flag. Example:

```bash
sinonimos --version
# sinonimos v0.1.0
```

See [mow.cli README](https://github.com/jawher/mow.cli#basics) for how to do it.

### Tasks

- [x] Add ability to print current version

**Comment by mateuszhoffman** [comment]
Let's do this! 👍

**Comment by felipemfp** [comment]
> Let's do this!

Go ahead! :tada:
